version: '3.7'

services:
  consul:
    image: defn/consul
    command:
      - -advertise
      - ${NODE_IP}
    env_file: .env
    ports:
      - "8600:8600/tcp"
      - "8600:8600/udp"
      - "8500:8500/tcp"
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
    volumes:
    - /mnt/consul:/consul/data
    restart: always
