version: '3.7'

services:
  consul:
    image: defn/consul
    ports:
      - "8600:8600/tcp"
      - "8600:8600/udp"
      - "8500:8500/tcp"
      - "8300:8300/tcp"
      - "8301:8301/tcp"
      - "8301:8301/udp"
      - "8302:8302/tcp"
      - "8302:8302/udp"
    volumes:
      - ${CONSUL_MOUNT:-./mnt}/consul:/consul/data
      - env_consul:/secrets
    restart: always

volumes:
  env_consul:
    external: true
